import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import DefaultProviders from "@/components/default-providers";
import Footer from "@/components/Footer";
import { CartProvider } from "@/context/cartContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <CartProvider>
          <DefaultProviders>
            <div className="container">
              <Header />
              {children}
              <Footer />
            </div>
          </DefaultProviders>
        </CartProvider>
      </body>
    </html>
  );
}
